// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugeCLY9fF_AOGaE_HZpg-R421gqpmWW0',
    appId: '1:979483497394:ios:a17e6241f9908cd8a28aab',
    messagingSenderId: '979483497394',
    projectId: 'cat-a-log-tracker',
    storageBucket: 'cat-a-log-tracker.firebasestorage.app',
    iosBundleId: 'com.example.catALog',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeTdonE_QOUezSf6tl68dVM4jaxEOMGd4',
    appId: '1:979483497394:web:1d5272b787bce23da28aab',
    messagingSenderId: '979483497394',
    projectId: 'cat-a-log-tracker',
    authDomain: 'cat-a-log-tracker.firebaseapp.com',
    storageBucket: 'cat-a-log-tracker.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUM9RSKxXdedoqEqjsdFI-Mcrjs4GXZ40',
    appId: '1:998112166387:ios:a01f8f859e2fc4ee821286',
    messagingSenderId: '998112166387',
    projectId: 'cat-a-log-2a7a9',
    storageBucket: 'cat-a-log-2a7a9.firebasestorage.app',
    iosBundleId: 'com.example.catTrackerApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQL__r4lSwc0JQgBIfZ0j0iniSFNt-980',
    appId: '1:998112166387:android:08ebeb49ede08b04821286',
    messagingSenderId: '998112166387',
    projectId: 'cat-a-log-2a7a9',
    storageBucket: 'cat-a-log-2a7a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh032MpjgoG-Teb0eBNsODIWrbKZzsKLU',
    appId: '1:998112166387:web:e18d0f1c428998de821286',
    messagingSenderId: '998112166387',
    projectId: 'cat-a-log-2a7a9',
    authDomain: 'cat-a-log-2a7a9.firebaseapp.com',
    storageBucket: 'cat-a-log-2a7a9.firebasestorage.app',
    measurementId: 'G-E84TCFC0CW',
  );

}